### ISSUE TITLE
Weights of the Portfolio Optimisation

### ISSUE THREAD

**Issue by andrewcztrack** [OscarJHernandez/qc_portfolio_optimization#5]
Hi @OscarJHernandez !

I hope your well!

I am really interested in the algorithm and I am looking to build it.

I was just wondering where in the notebook can i get the weights of the portfolio and can i set a constraint that an asset has to be at least 5% of the portfolio?

Kind regards and thanks,
Andrew

**Comment by OscarJHernandez** [comment]
Thanks for your question. The weights are only integers w_k = {-1,0,1}. This problem is framed as a combinatorial optimization problem and doesn't have continuous values for the weights.

The current version of the algorithm can only handle similar types of constraints. For example, one of the assets must be +1, 0 or -1. Let me know if you understood.

**Comment by OscarJHernandez** [comment]
I would highly recommend you look at the original paper from Rigetti. What is implemented in that paper is what I have done here with the addition of soft constraints. Constraints that are not in the original paper will have to be added by hand into the circuit as either a soft or hard constraint.

https://arxiv.org/abs/1911.05296

**Comment by andrewcztrack** [comment]
Hi @OscarJHernandez !!! Thank you!!

So if there are 4 instruments in a portfolio what is an example of the weights of the 4 instruments?
would it be {1,0,-1} for each instrument?

Kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
Hi @OscarJHernandez !!

Hope your well!!
I have been having a closer read of the paper and the code.
So if I was to backtest this, let say the output is 1,0,-1 for three instruments.
Does that mean i go 50% long, 0, 50% short for the three instruments.

This would then form the equity curve?

Kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
Hi @OscarJHernandez ! I hope your well.
Just a note, I tried running the notebook but unfortunately got the below error.


Brute force search calculation
Here we compute the optimal solution using a brute-force search.

# Instantiate the portfolio 
portfolio1 = utils.Portfolio(N_portfolio=N_portfolio)
​
# Get the benchmark parameters
benchmark_parameters = portfolio1.benchmark_values()
​
# Determine the results via a bruteforce search
best_bruteforce_result = portfolio1.brute_force_search(benchmark_parameters)
​
# Provide the optimal energy along with the state
print('='*100)
print('Brute-Force state: ', best_bruteforce_result['minimum_cost_states'])
print('Brute-Force energy: ', best_bruteforce_result['minimum_cost'])
print('='*100)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-e3d831fbf95a> in <module>
      1 # Instantiate the portfolio
----> 2 portfolio1 = utils.Portfolio(N_portfolio=N_portfolio)
      3 
      4 # Get the benchmark parameters
      5 benchmark_parameters = portfolio1.benchmark_values()

~/qc_portfolio_optimization/src/qc_utils.py in __init__(self, N_portfolio, mu, sigma, lam)
     34 
     35         # Instantiate the returns vector
---> 36         self.mu = [Parameter("mu_"+str(k)) for k in range(N_portfolio)]
     37 
     38         # instantiate the sigma matrix

~/qc_portfolio_optimization/src/qc_utils.py in <listcomp>(.0)
     34 
     35         # Instantiate the returns vector
---> 36         self.mu = [Parameter("mu_"+str(k)) for k in range(N_portfolio)]
     37 
     38         # instantiate the sigma matrix

NameError: name 'Parameter' is not defined

**Comment by OscarJHernandez** [comment]
For example, if you have four securities a solution would be a vector-like x = [-1,1,1,0], indicating that you should short the first security, then hold security 2 and 3 and not have any position in the fourth. But this is explained in the article I linked to before, and also in my blog-post: https://www.zorc-finance.com/post/optimal-portfolios-with-qaoa 

This is a combinatorial problem, so the algorithm solution is a discrete combination not a percentage. To convert to the percentage you must normalize the solution by the sum of the vector "x".  

With respect to the run-issue, that is something else, I will open a new issue. I will close the current issue now.
